# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  push: {}
#   schedule:
#   - cron: '*/5 * * * *'

jobs:
  stale-job:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    outputs:
      staled-prs-output: ${{ steps.step-stale.outputs.staled_prs }}

    steps:
    - uses: actions/stale@v7
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: 'This PR is stale because it has been open 45 days with no activity. Remove stale label or comment or this will be closed in 1 days.'
        days-before-pr-stale: 0.11
        ignore-updates: true
    - name: Print outputs
      id: step-stale
      env:
        STALE_PRS: ${{ steps.step-stale.outputs.staled-issues-prs }}
      run: |
        echo "Stale PRs count ${#STALE_PRS[@]}"
        echo "staled_prs=${#STALE_PRS[@]}" >> $GITHUB_OUTPUT # Command to set output, to be use in `notify-team-job` -> https://urlis.net/tpvquv5p
        
#   notify-team-job:
#     runs-on: ubuntu-latest
#     needs: stale-job
#     steps:
#       - name: Print outputs
#         env:
#           STALE_PRS_OUTPUT: ${{needs.stale-job.outputs.staled-prs-output}}
#         run: echo "say oh yeah $STALE_PRS_OUTPUT"
  notify-team-job:
    runs-on: ubuntu-latest
    needs: stale-job
    steps:
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        env:
          STALE_PRS_OUTPUT: ${{ needs.stale-job.outputs.staled-prs-output }}
        with:
          STALE_PRS_OUTPUT: ${{ needs.stale-job.outputs.staled-prs-output }}
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          overwrite: "{title: `We have $STALE_PRS_OUTPUT staled PRs. Please give it some attention`}"
      - name: Print output
        env:
          STALE_PRS_OUTPUT: ${{ needs.stale-job.outputs.staled-prs-output }}
        run: echo "We have $STALE_PRS_OUTPUT staled PRs"
