# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  push: {}
  schedule:
  - cron: '*/5 * * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
#     outputs:
#       output1: ${{ steps.step1.outputs.staled-issues-prs }}

    steps:
    - uses: actions/stale@v7
#       id: step1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: 'This PR is stale because it has been open 45 days with no activity. Remove stale label or comment or this will be closed in 10 days.'
        days-before-pr-stale: 0.1
  job2:
    runs-on: ubuntu-latest
    needs: stale
    steps:
      - env:
          OUTPUT1: ${{needs.stale.outputs.staled-issues-prs}}
          OUTPUT2: ${{needs.stale.outputs.closed-issues-prs}}
        run: echo "say oh yeah $OUTPUT1 $OUTPUT2"
#   job-notify-teams:
#     runs-on: ubuntu-latest
#     needs: stale
#     permissions:
#       issues: write
#       pull-requests: write
#     env:
#       OUTPUT1: ${{ needs.stale.outputs.staled-issues-prs }}
#     steps:
#       - uses: skitionek/notify-microsoft-teams@master
#         with:
#           webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
#           overwrite: "{title: `Overwrote title in $OUTPUT1`}"
#       - run: "echo $OUTPUT1"
